=== templatestudio/templatestudio-core_-_2.1.0/etc/vendor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2016 Template Studio UK. All rights reserved.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="property">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="code" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="adr">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
			<xs:attribute type="xs:string" name="code" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="org" type="xs:string" />
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="adr" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="url">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="email">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="config">
		<xs:annotation>
			<xs:documentation>TemplateStudio UK</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="org" />
				<xs:element ref="address" />
				<xs:element ref="url" />
				<xs:element ref="email" />
				<xs:element ref="phone" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== templatestudio/templatestudio-core_-_2.1.0/etc/vendor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    TemplateStudio UK
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Templatestudio_Core:etc/vendor.xsd">
    <org>Template Studio UK</org>
    <address>
        <adr code="default">
            <property code="street">21 Hockliffe Brae</property>
            <property code="locality">Walnut Tree</property>
            <property code="region">Milton Keynes</property>
            <property code="postalcode">MK7 7BG</property>
            <property code="country">United Kingdom</property>
        </adr>
    </address>
    <url>
        <property code="vendor">http://www.templatestudio.com/</property>
        <property code="feed">http://www.templatestudio.com/feed/file.rss</property>
        <property code="extension">http://www.templatestudio.com/extmanager/extension/feed/</property>
        <property code="license">http://www.templatestudio.com/extmanager/extension/license/</property>
        <property code="quote">http://www.templatestudio.com/quote/</property>
    </url>
    <email>
        <property code="sales">sales@templatestudio.com</property>
        <property code="contact">contact@templatestudio.com</property>
    </email>
    <phone>
        <property code="default">+44 1 908 766443</property>
        <property code="us">+1 347 284 0154</property>
    </phone>
</config>
